name: Grading

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grade
        # replace README.MD with https://raw.githubusercontent.com/ViMaSter/github-starter-course-test/main/README.md
        # check if there's a git difference
        run: |
          cd $GITHUB_WORKSPACE
          curl -s https://raw.githubusercontent.com/ViMaSter/github-starter-course-test/main/README.md > README.MD
          git diff
          git diff --exit-code
          # check if last exit code was 1 then exit with 0
          test $? -eq 1 && exit 0          
