name: Grading

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # checkout current branch to $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      - name: Grade
        # replace README.md with https://raw.githubusercontent.com/ViMaSter/github-starter-course-test/main/README.md
        # check if there's a git difference
        run: |
          cd $GITHUB_WORKSPACE
          cat README.md
          curl -s https://raw.githubusercontent.com/ViMaSter/github-starter-course-test/main/README.md > README.md
          echo "after curl"
          cat README.md
          # run git diff but don't exit on error but capture exit code
          exit_code=0
          git diff --exit-code || exit_code=$?
          echo "git diff exit code: $exit_code"
          if [ $exit_code -eq 0 ]; then
            exit 1
          else
            exit 0
          fi
